---
development:
  DB_FILENAME: app/infrastructure/database/local/dev.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token
  FREECURRENCY_API_KEY: This_Is_A_Sample_FreeCurrency_API_KEY
  SESSION_SECRET: asdfqwerzxcv
  APP_HOST: http://127.0.0.1:4001
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  EXTRACTOR_QUEUE: <queue name>
  EXTRACTOR_QUEUE_URL: <set by AWS>

test:
  DB_FILENAME: app/infrastructure/database/local/test.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token
  FREECURRENCY_API_KEY: This_Is_A_Sample_FreeCurrency_API_KEY
  SESSION_SECRET: asdfqwerzxcv
  APP_HOST: http://127.0.0.1:4001
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  EXTRACTOR_QUEUE: <queue name>
  EXTRACTOR_QUEUE_URL: <set by AWS>

# Keep production info here so we can remember to set them on Heroku
production:
  DB_FILENAME: app/infrastructure/database/local/test.db
  REED_TOKEN: This_Is_A_Sample_Reed_Token
  FREECURRENCY_API_KEY: This_Is_A_Sample_FreeCurrency_API_KEY
  SESSION_SECRET: asdfqwerzxcv
  APP_HOST: http://127.0.0.1:4001
  REDISCLOUD_URL: url-assigned-by-Redis-provider-on-Heroku
  AWS_ACCESS_KEY_ID: <aws credential>
  AWS_SECRET_ACCESS_KEY: <aws credential>
  AWS_REGION: <choose region>
  EXTRACTOR_QUEUE: <queue name>
  EXTRACTOR_QUEUE_URL: <set by AWS>
